
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INTEGER AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  anniversary VARCHAR(10) DEFAULT NULL,
  cpf VARCHAR(11) DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(25) DEFAULT null ,
  email VARCHAR(250) DEFAULT NULL

);