
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INTEGER AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  anniversary VARCHAR(250) DEFAULT NULL,
  cpf VARCHAR(20) DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(250) DEFAULT null ,
  email VARCHAR(250) DEFAULT NULL

);